package com.sap.tpch.tables;

import com.sap.tpch.db_interaction.DBExecutor;
import com.sap.tpch.exception.PrepException;
import com.sap.tpch.remoute.PreparationMonitor;

import java.sql.SQLException;

/**
 * Created by Alex on 10.10.2014.
 * Contain base methods for all tables.
 */
public interface ITableGenerator {

    /**
     * Execute script for uploading data to database.
     */
    public void importData(DBExecutor executor, PreparationMonitor preparationMonitor) throws PrepException;

    /**
     * Execute script for create table.
     */
    public void createTable(DBExecutor executor, PreparationMonitor preparationMonitor) throws PrepException;

    /**
     * Execute script for drop table.
     */
    public void dropTable(DBExecutor executor, PreparationMonitor preparationMonitor) throws PrepException;

    /**
     * Load table data into memory
     */
    public void loadTableDataIntoMemory(DBExecutor executor, PreparationMonitor preparationMonitor) throws PrepException;

    /**
     * Check if table exist in database.
     * @param executor DBExecutor.
     * @return @tue if table exist, @false another case.
     * @throws PrepException
     */
    public boolean isTableExist(DBExecutor executor) throws PrepException;

    /**
     * Check if all data loaded in table.
     * @param executor database executor.
     * @return @true if all data added in table, @false another case.
     * @throws PrepException
     */
    public boolean isDataInTables(DBExecutor executor) throws PrepException;

    /**
     * Execute table name generated by dbgen program.
     * @return table name generated by dbgen program.
     */
    public String getGeneratedTableName();

    /**
     * Get table name.
     * @return table name.
     */
    public String getTableName();

    /**
     * Get base row number of table.
     * @return base row number of table.
     */
    public int getBaseRowsNumber();
}
