package com.sap.hana.tpch.tables;

import com.sap.hana.tpch.types.ScaleFactor;

/**
 * Created by Alex on 10.10.2014.
 * Contain base for different Databases information about tables.
 */
abstract public class BaseTable implements ITableGenerator{

    /**
     * Scale factor value.
     */
    ScaleFactor scaleFactor;

    protected BaseTable(){}

    public BaseTable(ScaleFactor scaleFactor){
        this.scaleFactor = new ScaleFactor(scaleFactor);
    }

    /**
     * return scale factor.
     * @return scale factor.
     */
    protected ScaleFactor getScaleFactor(){
        return scaleFactor;
    }

    /**
     * Get name of table base on Class name.
     * Table class name is __[some_table_name]. Method get some_table_name and return it.
     * @param className name of class starting with T...
     * @return Name of table.
     */
    public static String getClassTableName(Class className){
        String[] arr = className.getName().split("\\.");
        if(arr.length<2) return "";
        return arr[arr.length-1].substring(2).toUpperCase();
    }

    /**
     * Gen name of file generated by dbgen, containing data.
     * @return name of file generated by dbgen.
     */
    public String getGeneratedTableName(){
        return getClassTableName(this.getClass()).toLowerCase()+".tbl";
    }

    /**
     * Get name of file generated by dbgen.
     * Table class name is T(some_table_name). Method get some_table_name in low case and add .tbl extension to end.
     * @return name of table
     */
    public String getTableName(){
        return getClassTableName(this.getClass());
    }

}
