package com.sap.hana.tpch.tables;

/**
 * Created by Alex on 10.10.2014.
 * Contain base methods for all tables.
 */
public interface ITableGenerator {

    /**
     * Get script for uploading data to database.
     * @return script for uploading data to database.
     */
    public String getUploadingScript();

    /**
     * Get script for create table.
     * @return script for create table.
     */
    public String getCreateScript();

    /**
     * Get script for drop table.
     * @return
     */
    public String getDeleteScript();

    /**
     * Get table name generated by dbgen program.
     * @return table name generated by dbgen program.
     */
    public String getGeneratedTableName();

    /**
     * Get table name.
     * @return table name.
     */
    public String getTableName();

    /**
     * Get base row number of table.
     * @return base row number of table.
     */
    public int getBaseRowsNumber();
}
